import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/lib/providers";
// import { Provider } from "react-redux";
// import store from "../store/store.js";
import Capsule from "./caps";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";



import { ReduxProvider } from "../store/provider";


import "./globals.css";
// import Navbar from "./components/Navbar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
// import createAxiosInstance from "./apis/config";

// const axiosInstance = createAxiosInstance(store);

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="h-full">
			<head>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
					integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
					crossOrigin="anonymous"
					referrerPolicy="no-referrer"
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ReduxProvider>
					<Providers>
						<Capsule>
							{children}
						</Capsule>
					</Providers>
				</ReduxProvider>
			</body>
		</html>
	);
}